#!/bin/sh
# Run this to generate all the initial makefiles, etc.

echo "Generating configuration files for gnome-themes, please wait...."
echo;

for theme in LargePrint HighContrast HighContrastLargePrint HighContrastInverse HighContrastLargePrintInverse LowContrast LowContrastLargePrint;  do
	echo "Generating $theme/gtk-2.0/gtkrc.in"
	echo "#======" > $theme/gtk-2.0/gtkrc.in
	echo "#This file was generated by autogen.sh." >> $theme/gtk-2.0/gtkrc.in
	echo "#Do not edit it by hand if building from cvs." >> $theme/gtk-2.0/gtkrc.in
	echo "#See README for more details." >> $theme/gtk-2.0/gtkrc.in
	echo "#======" >> $theme/gtk-2.0/gtkrc.in
	cat $theme/gtk-2.0/$theme.rc common/gtk-stock-icons.rc common/panel-stock-icons.rc common/media-stock-icons.rc common/capplet-stock-icons.rc common/metacity-stock-icons.rc >> $theme/gtk-2.0/gtkrc.in
done

for theme in LargePrint HighContrastLargePrint HighContrastLargePrintInverse LowContrastLargePrint; do
	echo "Generating $theme/pixmaps/Makefile.am"
	cat common/all-stock-icons.data $theme/pixmaps/$theme.makefile > $theme/pixmaps/Makefile.am

done


srcdir=`dirname $0`
test -z "$srcdir" && srcdir=.

ORIGDIR=`pwd`
cd $srcdir
PKG_NAME=gnome-themes
REQUIRED_AUTOMAKE_VERSION=1.7
USE_GNOME2_MACROS=1

AUTOMAKE=automake-1.7
ACLOCAL=aclocal-1.7

if [ ! -f "$srcdir/gnome-themes.spec.in" ]; then
 echo "$srcdir doesn't look like source directory for $PKG_NAME" >&2
 exit 1
fi

. gnome-autogen.sh

